// Shared types for the ingest worker + cron handler.
//
// `Env` mirrors the bindings declared in `wrangler.toml`. Keep names exact —
// Cloudflare injects each binding as a property of the second handler argument.

export interface Env {
    ANALYTICS_DB: D1Database;
    ENVIRONMENT: string;
    ALLOWED_ORIGINS: string;
    PLAUSIBLE_DOMAIN: string;
    DIGEST_RECIPIENT: string;
    DIGEST_FROM: string;
    // Secrets — present only after `wrangler secret put`. Treat as optional
    // so `pnpm test` and local dev work without secrets configured.
    INGEST_KEY?: string;
    RESEND_API_KEY?: string;
    PLAUSIBLE_API_KEY?: string;
}

// Canonical event names from PLG §7.1 — keep this union closed so a typo at
// a call-site is caught at compile time. New events MUST land here first
// before being emitted.
export type EventName =
    // Acquisition
    | "landing_view"
    | "landing_cta_click"
    | "signup_started"
    | "signup_completed"
    // Onboarding
    | "tenant_created"
    | "pat_issued"
    | "welcome_view"
    // Activation pre-cursors + canonical activation event
    | "first_cli_authed"
    | "first_cas_write"
    | "first_cache_hit"
    // Engagement
    | "cache_hits_10"
    | "cache_hits_100"
    | "cache_hits_1k"
    | "team_member_invited"
    // Monetization
    | "pricing_view"
    | "checkout_started"
    | "paid_subscription_started"
    | "plan_downgraded"
    | "subscription_canceled";

export interface EventPayload {
    // ULID generated by the client. Re-POSTing the same id is a no-op.
    id: string;
    event_name: EventName;
    tenant_id?: string | null;
    user_id?: string | null;
    session_id?: string | null;
    properties?: Record<string, unknown>;
    // Optional client-supplied timestamp (ISO-8601). If absent, server uses
    // its own `now()`. Provided so the cas-worker can backfill `seconds_since_*`
    // calculations from its own monotonic clock.
    created_at?: string;
}
