import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Diátaxis 4-quadrant sidebar structure.
 *
 * The four canonical Diátaxis modes — tutorial (learning-oriented),
 * how-to (task-oriented), reference (information-oriented), and
 * explanation (understanding-oriented) — are first-class top-level
 * categories. WI-S18-001 establishes the structure; WI-S18-002..004
 * populate the items.
 *
 * Per Quality Standard 14.s18.2, every documentation page MUST be filed
 * under exactly one of these four categories. PR review enforces this.
 */
const sidebars: SidebarsConfig = {
  defaultSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Welcome",
    },
    {
      type: "category",
      label: "Get Started",
      link: { type: "doc", id: "tutorial/index" },
      collapsed: false,
      items: [
        // 10-minute quickstart — promoted to the top of Get Started
        // per R-8 GA launch checklist (single most-clicked post-launch
        // doc; validated by .github/workflows/quickstart-validate.yml).
        "tutorials/quickstart-10min",
        "tutorials/quickstart-faq",
        "tutorial/01-installation",
        "tutorial/02-first-pat",
        "tutorial/03-bazel-quickstart",
        "tutorial/04-buck2-quickstart",
        "tutorial/05-native-ffi-quickstart",
        "tutorial/06-verify-cache-hit",
      ],
    },
    {
      type: "category",
      label: "How-to",
      link: { type: "doc", id: "how-to/index" },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "RBAC",
          collapsed: true,
          items: [
            "rbac-invite-team-member",
            "rbac-audit-role-changes",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "doc", id: "reference/index" },
      collapsed: true,
      items: [
        {
          type: "category",
          label: "REAPI v2",
          collapsed: true,
          items: [
            "reference/reapi/index",
            {
              type: "autogenerated",
              dirName: "reference/reapi/_generated",
            },
          ],
        },
        {
          type: "category",
          label: "REST API",
          collapsed: true,
          // Landing (auto-generated) + raw OpenAPI spec page + one
          // auto-discovered MDX per endpoint under endpoints/.
          // The endpoint set is regenerated from
          // openapi/corelink-v1.yaml by
          // `scripts/gen-api-reference.py`; drift is gated by
          // `.github/workflows/api-reference-sync.yml`.
          items: [
            "reference/api/index",
            "reference/api/openapi",
            {
              type: "category",
              label: "Endpoints",
              collapsed: true,
              items: [
                {
                  type: "autogenerated",
                  dirName: "reference/api/endpoints",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "RBAC",
          collapsed: true,
          items: ["rbac-permissions"],
        },
      ],
    },
    {
      type: "category",
      label: "Explanation",
      link: { type: "doc", id: "explanation/architecture" },
      collapsed: true,
      items: [
        "explanation/architecture",
        {
          type: "category",
          label: "Residency",
          collapsed: true,
          items: ["explanation/residency/lgpd-brazil"],
        },
        {
          type: "category",
          label: "RBAC",
          collapsed: true,
          items: [
            "rbac-overview",
            "rbac-role-catalog",
            "rbac-permission-matrix",
          ],
        },
      ],
    },
    // Customer-facing Trust Center — top-level category alongside the
    // Diátaxis quadrants so procurement / DPO traffic can find compliance
    // posture, sub-processors, and IR in one place per R-8 launch checklist
    // (LAUNCH-CHECKLIST-V2.md row L23: "Trust center unlock").
    {
      type: "category",
      label: "Trust",
      link: { type: "doc", id: "trust/index" },
      collapsed: true,
      items: [
        "trust/compliance",
        "trust/data-handling",
        "trust/subprocessors",
        "trust/incident-response",
      ],
    },
  ],
};

export default sidebars;
