// Sidebar config typed as `any` until Docusaurus types are wired in WI-S18-001
// scaffold (the type lives in @docusaurus/plugin-content-docs which is pulled
// transitively by @docusaurus/preset-classic).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SidebarsConfig = any;

// Diataxis quadrants: Tutorial (learning), How-to (problem-solving),
// Reference (information), Explanation (understanding).
const sidebars: SidebarsConfig = {
  tutorial: [
    {
      type: "category",
      label: "Getting started",
      collapsed: false,
      items: [
        "tutorial/01-installation",
        "tutorial/02-first-pat",
        "tutorial/03-bazel-quickstart",
        "tutorial/04-buck2-quickstart",
        "tutorial/05-native-ffi-quickstart",
        "tutorial/06-verify-cache-hit",
      ],
    },
  ],
  reference: [
    {
      type: "category",
      label: "REAPI v2",
      collapsed: false,
      items: [
        "reference/reapi/index",
        {
          type: "autogenerated",
          dirName: "reference/reapi/_generated",
        },
      ],
    },
  ],
};

export default sidebars;
