from __future__ import annotations

from pathlib import Path

import pytest

import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
import verify_b326_loc_cap as verify


def test_current_manifest_and_population_pass() -> None:
    verify.verify()
    verify.self_test()


def test_new_source_over_500_lines_is_rejected() -> None:
    baseline_paths, _ = verify._parse_manifest(verify.MANIFEST.read_text(encoding="utf-8"))
    target = sorted(verify._tracked_source_paths(verify.ROOT) - baseline_paths)[0]
    source = (verify.ROOT / target).read_text(encoding="utf-8")
    mutated = source + "\n" + "\n".join("// mutation" for _ in range(verify.MAX_LOC + 1))
    with pytest.raises(verify.VerificationError, match="HARD-CAP"):
        verify.verify(overrides={target: mutated})


def test_manifest_digest_and_baseline_identity_are_required() -> None:
    manifest = verify.MANIFEST.read_text(encoding="utf-8")
    with pytest.raises(verify.VerificationError):
        verify._parse_manifest(manifest.replace(verify.BASELINE_SHA, "0" * 40, 1))
    with pytest.raises(verify.VerificationError):
        verify._parse_manifest(manifest.replace("source-path-count: 2443", "source-path-count: 2442", 1))


def test_generated_exception_requires_reviewed_path_and_exact_header() -> None:
    policy = verify.GENERATED_SOURCE_ALLOWLIST["worker/src/lib/openapi_v1.ts"]
    header, generator = policy
    valid = f"{header}\n// DO NOT EDIT\n" + ("x\n" * (verify.MAX_LOC + 1))
    assert verify._generated_exception(
        valid,
        relative="worker/src/lib/openapi_v1.ts",
        root=verify.ROOT,
    )
    assert not verify._generated_exception(
        valid,
        relative="hand-written.ts",
        root=verify.ROOT,
    )
    assert not verify._generated_exception(
        valid.replace(header, "// @generated by " + generator, 1),
        relative="worker/src/lib/openapi_v1.ts",
        root=verify.ROOT,
    )


def test_oversized_handwritten_source_cannot_opt_out_with_marker() -> None:
    baseline_paths, _ = verify._parse_manifest(verify.MANIFEST.read_text(encoding="utf-8"))
    target = "hand-written-marker.ts"
    source = "// @generated\n" + ("marker\n" * (verify.MAX_LOC + 1))
    with pytest.raises(verify.VerificationError, match="HARD-CAP"):
        verify.verify(
            tracked_paths=baseline_paths | {target},
            overrides={target: source},
        )
