import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { describe, expect, it } from "vitest";
import { readLegacyCredentialCoverage } from "../src/lib/credential_legacy_coverage.js";
const { DatabaseSync } = createRequire(import.meta.url)("node:sqlite") as typeof import("node:sqlite");
const TENANT = "11111111-1111-4111-8111-111111111111";
class D1 { readonly sqlite = new DatabaseSync(":memory:"); constructor() { this.sqlite.exec("CREATE TABLE runner_credential_obligation (operation_id TEXT, tenant_id TEXT, pat_id TEXT); CREATE TABLE devenv_credential_obligation (operation_id TEXT, tenant_id TEXT, pat_id TEXT); CREATE TABLE customer_audit_events (tenant_id TEXT, event_type TEXT, target TEXT); CREATE TABLE pat (pat_id TEXT, tenant_id TEXT, token_id TEXT, runner_job_ac_key TEXT, revoked_at_ms INTEGER, expires_ms INTEGER);"); this.sqlite.exec(readFileSync(new URL("../../migrations/d1/0129_credential_lifecycle_generation.sql", import.meta.url), "utf8")); } prepare(sql: string) { const db = this.sqlite; return { bind: (...a: unknown[]) => { const values = [...sql.matchAll(/\?(\d+)/g)].map(m => a[Number(m[1]) - 1]); const q = sql.replace(/\?(\d+)/g, "?"); return { first: async <T>() => db.prepare(q).get(...values) as T | undefined ?? null }; } }; } }
const ID = "22222222-2222-4222-8222-222222222222";
function add(db: D1, marker: string | null, expires = 4102444800000) { db.sqlite.prepare("INSERT INTO pat VALUES (?, ?, ?, ?, ?, ?, ?)").run(ID, TENANT, "tok", marker, null, expires, "0"); }
describe("legacy credential coverage", () => {
  it("requires a floor and known, non-active legacy inventory", async () => { const db = new D1(); db.sqlite.prepare("INSERT INTO tenant_credential_revocation_floor VALUES (?, ?)").run(TENANT, "0"); expect(await readLegacyCredentialCoverage(db as never, TENANT, "0")).toEqual({ complete: false }); add(db, "*"); expect(await readLegacyCredentialCoverage(db as never, TENANT, "0")).toEqual({ complete: false }); db.sqlite.prepare("UPDATE pat SET revoked_at_ms=1").run(); expect(await readLegacyCredentialCoverage(db as never, TENANT, "0")).toEqual({ complete: true }); });
  it("fails closed for newer or malformed rows and wrong identity", async () => { const db = new D1(); db.sqlite.prepare("INSERT INTO tenant_credential_revocation_floor VALUES (?, ?)").run(TENANT, "0"); add(db, "ac"); db.sqlite.prepare("UPDATE pat SET lifecycle_generation='2'").run(); expect(await readLegacyCredentialCoverage(db as never, TENANT, "0")).toEqual({ complete: false }); await expect(readLegacyCredentialCoverage(db as never, "bad", "0")).rejects.toThrow(); });
  it("accepts customer-audit proof when no runner marker exists", async () => { const db = new D1(); db.sqlite.prepare("INSERT INTO tenant_credential_revocation_floor VALUES (?, ?)").run(TENANT, "0"); add(db, null); db.sqlite.prepare("UPDATE pat SET revoked_at_ms=1").run(); db.sqlite.prepare("INSERT INTO customer_audit_events VALUES (?, ?, ?)").run(TENANT, "pat.created", ID); expect(await readLegacyCredentialCoverage(db as never, TENANT, "0")).toEqual({ complete: true }); });
});
