import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { describe, expect, it } from "vitest";
import { readLegacyCredentialCoverage } from "../src/lib/credential_legacy_coverage.js";
const { DatabaseSync } = createRequire(import.meta.url)("node:sqlite") as typeof import("node:sqlite");
const TENANT = "11111111-1111-4111-8111-111111111111";
class D1 { readonly sqlite = new DatabaseSync(":memory:"); constructor() { this.sqlite.exec("CREATE TABLE runner_credential_obligation (operation_id TEXT PRIMARY KEY, tenant_id TEXT, job_id TEXT, repo TEXT, state TEXT, deadline_ms INTEGER, pat_id TEXT, token_id TEXT); CREATE TABLE devenv_credential_obligation (operation_id TEXT PRIMARY KEY, tenant_id TEXT, state TEXT, deadline_ms INTEGER, pat_id TEXT, token_id TEXT); CREATE TABLE pat (pat_id TEXT PRIMARY KEY, tenant_id TEXT, pat_hash TEXT, token_id TEXT, runner_job_ac_key TEXT, revoked_at_ms INTEGER, expires_ms INTEGER);"); this.sqlite.exec(readFileSync(new URL("../../migrations/d1/0129_credential_lifecycle_generation.sql", import.meta.url), "utf8")); this.sqlite.exec(readFileSync(new URL("../../migrations/d1/0077_customer_audit_events.sql", import.meta.url), "utf8")); } prepare(sql: string) { const db=this.sqlite; return { bind:(...a:unknown[])=>{ const values=[...sql.matchAll(/\?(\d+)/g)].map(m=>a[Number(m[1])-1]); const normalized=sql.replace(/\?(\d+)/g,"?"); return { first:async<T>()=>db.prepare(normalized).get(...values) as T|undefined??null, run:async()=>{const r=db.prepare(normalized).run(...values);return {success:true,meta:{changes:Number(r.changes)}}}, all:async<T>()=>({results:db.prepare(normalized).all(...values) as T[]})}; }}; } }
function add(db:D1,id:string,gen:string|null="0",expires=4102444800000,runner:string|null=null) { db.sqlite.prepare("INSERT INTO pat (pat_id,tenant_id,pat_hash,token_id,runner_job_ac_key,expires_ms,lifecycle_generation) VALUES (?,?,?,?,?,?,?)").run(id,TENANT,"h",`tok-${id}`,runner,expires,gen); }
const ID="22222222-2222-4222-8222-222222222222";
describe("legacy credential coverage",()=>{
  it("requires known history before customer audit can qualify",async()=>{const db=new D1();db.sqlite.prepare("INSERT INTO tenant_credential_revocation_floor(tenant_id,revoked_through) VALUES(?,?)").run(TENANT,"0");expect(await readLegacyCredentialCoverage(db as never,TENANT,"0")).toEqual({complete:false});add(db,ID);db.sqlite.prepare("INSERT INTO customer_audit_events(tenant_id,event_type,target,ts_ms) VALUES(?,?,?,?)").run(TENANT,"pat.created",ID,1);expect(await readLegacyCredentialCoverage(db as never,TENANT,"0")).toEqual({complete:false});add(db,"44444444-4444-4444-8444-444444444444","0",1,"*");expect(await readLegacyCredentialCoverage(db as never,TENANT,"0")).toEqual({complete:true});});
  it("does not accept wrong-tenant proof or runner/customer conflicts",async()=>{const db=new D1();add(db,ID,"0",4102444800000,"ac");db.sqlite.prepare("INSERT INTO tenant_credential_revocation_floor VALUES(?,?)").run(TENANT,"0");db.sqlite.prepare("INSERT INTO customer_audit_events(tenant_id,event_type,target,ts_ms) VALUES(?,?,?,?)").run("33333333-3333-4333-8333-333333333333","pat.created",ID,1);expect(await readLegacyCredentialCoverage(db as never,TENANT,"0")).toEqual({complete:false});});
  it("keeps newer-only and malformed history pending",async()=>{const db=new D1();add(db,ID,"2",4102444800000,"ac");db.sqlite.prepare("INSERT INTO tenant_credential_revocation_floor VALUES(?,?)").run(TENANT,"0");expect(await readLegacyCredentialCoverage(db as never,TENANT,"0")).toEqual({complete:false});db.sqlite.prepare("UPDATE pat SET expires_ms=?").run("bad");expect(await readLegacyCredentialCoverage(db as never,TENANT,"0")).toEqual({complete:false});});
  it("does not use expired unmarked rows or invalid markers as history",async()=>{const db=new D1();add(db,ID,"0",1);db.sqlite.prepare("INSERT INTO tenant_credential_revocation_floor VALUES(?,?)").run(TENANT,"0");expect(await readLegacyCredentialCoverage(db as never,TENANT,"0")).toEqual({complete:false});db.sqlite.prepare("UPDATE pat SET runner_job_ac_key=?, expires_ms=?").run(Buffer.from("*"),1);expect(await readLegacyCredentialCoverage(db as never,TENANT,"0")).toEqual({complete:false});db.sqlite.prepare("UPDATE pat SET runner_job_ac_key=?").run("a".repeat(64));expect(await readLegacyCredentialCoverage(db as never,TENANT,"0")).toEqual({complete:true});});
});
