import { describe, expect, it, vi } from "vitest";
import type { DurableObjectStorage } from "@cloudflare/workers-types";
import { PREPARE_MS, prepareDevenvOperation, drainDevenvOperations } from "../src/lib/devenv_cleanup";
const op="00000000-0000-4000-8000-000000000001", tenant="00000000-0000-4000-8000-000000000002";
function store(){ const map=new Map<string,unknown>(); let alarm:number|null=null; const events:string[]=[]; const io:any={put:vi.fn(async(k:string,v:unknown)=>{events.push("put");map.set(k,v)}),get:vi.fn(async(k:string)=>map.get(k)),delete:vi.fn(async(k:string)=>map.delete(k)),list:vi.fn(async({prefix,limit}:{prefix:string,limit:number})=>new Map([...map].filter(([k])=>k.startsWith(prefix)).slice(0,limit))),getAlarm:vi.fn(async()=>alarm),setAlarm:vi.fn(async(v:number)=>{events.push("alarm");alarm=v}),transaction:vi.fn(async(fn:any)=>fn(io))}; return {io:io as DurableObjectStorage,map,events,alarm:()=>alarm}; }
function db(){const run=vi.fn(async()=>({success:true,meta:{changes:1}}));const prepare=vi.fn((sql:string)=>({bind:(..._:unknown[])=>({run,first:async()=>({state:"revoking",token_id:"tok"}),all:async()=>({})}),all:async()=>({})}));const batch=vi.fn(async()=>[{success:true,meta:{changes:1}},{success:true,meta:{changes:1}},{success:true,meta:{changes:1}}]);return {db:{prepare,batch} as any,run,batch};}
describe("DevEnv cleanup",()=>{
 it("persists marker and alarm before D1 intent",async()=>{const s=store(),d=db();expect(await prepareDevenvOperation(s.io,d.db,op,tenant,1000,"0")).toBe(true);expect(s.events).toEqual(["put","alarm"]);expect(s.alarm()).toBe(1000+PREPARE_MS+2000);});
 it("does not process malformed markers",async()=>{const s=store(),d=db();s.map.set("devenv-cleanup/bad",{due:1});expect(await drainDevenvOperations(s.io,d.db,undefined,2)).toBe(true);expect(d.batch).not.toHaveBeenCalled();});
 it("bounds drain to four markers",async()=>{const s=store(),d=db();for(let i=0;i<6;i++){const id=`00000000-0000-4000-8000-00000000000${i+3}`;s.map.set(`devenv-cleanup/${id}`,{schema_version:1,operationId:id,tenantId:tenant, lifecycleGeneration:"0",deadline:1,due:1,attempts:0});}expect(await drainDevenvOperations(s.io,d.db,undefined,2)).toBe(true);expect(d.batch).toHaveBeenCalledTimes(4);});
});
