import { describe, expect, it, vi } from "vitest";
import type { DurableObjectStorage } from "@cloudflare/workers-types";
import { PREPARE_MS, prepareDevenvOperation, drainDevenvOperations } from "../src/lib/devenv_cleanup";
const op="00000000-0000-4000-8000-000000000001", tenant="00000000-0000-4000-8000-000000000002";
function store(){ const map=new Map<string,unknown>(); let alarm:number|null=null; const events:string[]=[]; const io:any={put:vi.fn(async(k:string,v:unknown)=>{events.push("put");map.set(k,v)}),get:vi.fn(async(k:string)=>map.get(k)),delete:vi.fn(async(k:string)=>map.delete(k)),list:vi.fn(async({prefix,limit}:{prefix:string,limit:number})=>new Map([...map].filter(([k])=>k.startsWith(prefix)).slice(0,limit))),getAlarm:vi.fn(async()=>alarm),setAlarm:vi.fn(async(v:number)=>{events.push("alarm");alarm=v}),transaction:vi.fn(async(fn:any)=>fn(io))}; return {io:io as DurableObjectStorage,map,events,alarm:()=>alarm}; }
function db(events:string[]=[]){const run=vi.fn(async()=>{events.push("d1");return {success:true,meta:{changes:1}}});const prepare=vi.fn((sql:string)=>({bind:(..._:unknown[])=>({run,first:async()=>({state:"revoking",token_id:"tok"}),all:async()=>({})}),all:async()=>({})}));const batch=vi.fn(async()=>[{success:true,meta:{changes:1}},{success:true,meta:{changes:1}},{success:true,meta:{changes:1}}]);return {db:{prepare,batch} as any,run,batch};}
describe("DevEnv cleanup",()=>{
 it("persists marker and alarm before D1 intent",async()=>{const s=store(),d=db(s.events);expect(await prepareDevenvOperation(s.io,d.db,op,tenant,1000,"0")).toBe(true);expect(s.events).toEqual(["put","alarm","d1"]);expect(s.alarm()).toBe(1000+PREPARE_MS+2000);});
 it("does not process malformed markers",async()=>{const s=store(),d=db();s.map.set("devenv-cleanup/bad",{due:1});expect(await drainDevenvOperations(s.io,d.db,undefined,2)).toBe(true);expect(d.batch).not.toHaveBeenCalled();});
 it("retains due work after D1 or KV failure and backs off",async()=>{const s=store(),d=db(),kv={delete:vi.fn().mockRejectedValueOnce(new Error("fault"))};const id="00000000-0000-4000-8000-000000000003";s.map.set(`devenv-cleanup/${id}`,{schema_version:1,operationId:id,tenantId:tenant,lifecycleGeneration:"0",deadline:1,due:1,attempts:0});expect(await drainDevenvOperations(s.io,d.db,kv,2)).toBe(true);expect(s.map.get(`devenv-cleanup/${id}`)).toMatchObject({attempts:1,due:2002});expect(await drainDevenvOperations(s.io,d.db,{delete:vi.fn()},2002)).toBe(false);});
 it("returns false for a batch whose obligation update changed zero rows",async()=>{const s=store(),d=db();d.batch.mockResolvedValueOnce([{success:true,meta:{changes:1}},{success:true,meta:{changes:0}}]);const ok=await (await import("../src/lib/devenv_cleanup")).activateDevenvPat(d.db,op,tenant,{pat_id:"pat",token_id:"tok",hash:"digest",expires_ms:10_000},"read-write","0");expect(ok).toBe(false);});
 it("diagnoses malformed evidence without deleting it",async()=>{const s=store(),d=db(),log=vi.spyOn(console,"error").mockImplementation(()=>{});try{s.map.set("devenv-cleanup/bad",{due:1});await drainDevenvOperations(s.io,d.db,undefined,2);expect(log).toHaveBeenCalledWith("malformed DevEnv cleanup marker retained");expect(s.map.has("devenv-cleanup/bad")).toBe(true);}finally{log.mockRestore();}});
 it("bounds drain to four markers",async()=>{const s=store(),d=db();for(let i=0;i<6;i++){const id=`00000000-0000-4000-8000-00000000000${i+3}`;s.map.set(`devenv-cleanup/${id}`,{schema_version:1,operationId:id,tenantId:tenant, lifecycleGeneration:"0",deadline:1,due:1,attempts:0});}expect(await drainDevenvOperations(s.io,d.db,undefined,2)).toBe(true);expect(d.batch).toHaveBeenCalledTimes(4);});
});
