/* Generated by cbindgen — do not edit by hand. */

#ifndef CORELINK_CLIENT_VERIFY_H
#define CORELINK_CLIENT_VERIFY_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#if defined(CORELINK_CLIENT_VERIFY_STREAM)
/**
 * Chunk size used by [`ClientVerifier::verify_stream`]. 64 KiB matches
 * the Tokio `AsyncRead` default + Cloudflare R2 streamed-read
 * recommendation. Each in-flight chunk plus the BLAKE3 hasher state
 * keeps peak memory < 2 MiB even for 5 MiB blobs.
 */
#define STREAM_CHUNK_BYTES (64 * 1024)
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * Raw BLAKE3 digest length (32 bytes). Re-emitted as a numeric
 * literal in the cbindgen C header so downstream C / Go / Python
 * wrappers reference a single canonical constant rather than
 * hard-coding `32`. Pinned to a literal (not
 * `corelink_hash::DIGEST_LEN`) because cbindgen with `parse_deps =
 * false` cannot resolve constants from the workspace dep tree —
 * the static assertion below keeps this literal in lockstep with
 * the upstream constant.
 */
#define DIGEST_BYTES 32
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * Hex-encoded digest length (`DIGEST_BYTES * 2` = 64). The C-ABI
 * verify entry point rejects any other length with
 * `COR_VERIFY_ERR_INVALID_DIGEST` before touching the digest
 * pointer's memory.
 */
#define DIGEST_HEX_LEN 64
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * `out_error_code` tag: success.
 */
#define COR_VERIFY_OK 0
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * `out_error_code` tag: digest mismatch.
 */
#define COR_VERIFY_ERR_MISMATCH 1
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * `out_error_code` tag: verifier was constructed via
 * [`corelink_verifier_new_disabled`] and the caller invoked verify
 * anyway. Production callers expecting opt-out should not invoke
 * verify at all; this tag exists so integration tests + audit logs
 * can route the explicit opt-out path through a stable code.
 */
#define COR_VERIFY_ERR_DISABLED 2
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * `out_error_code` tag: a required input pointer was null OR a length
 * was non-zero with a null pointer / inconsistent length. Returned by
 * the verify entry point before any hash work begins.
 */
#define COR_VERIFY_ERR_INVALID_INPUT 3
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * `out_error_code` tag: hex parse of the claimed digest failed
 * (length != 64 OR non-hex char).
 */
#define COR_VERIFY_ERR_INVALID_DIGEST 4
#endif

/**
 * Client-side BLAKE3 digest verifier.
 *
 * Constructed with a [`VerifyConfig`]; [`ClientVerifier::verify`] then
 * computes BLAKE3 of the body and compares against the claimed digest
 * in constant time. The default-on contract is enforced by
 * `VerifyConfig`: callers cannot construct a `ClientVerifier` whose
 * configuration silently opted out without going through the explicit
 * [`VerifyConfig::disabled`] path, which also emits a warning log +
 * counter increment.
 */
typedef struct CoreLinkClientVerifier CoreLinkClientVerifier;



#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * Allocate a new default-on opaque `ClientVerifier`. Pass the
 * returned handle back to [`corelink_verifier_verify`] and finally
 * release it via [`corelink_verifier_free`].
 *
 * This is the canonical SDK construction path: verify is enabled,
 * no warning fires (because nothing is being opted out), and the
 * `opt_out_total` counter does NOT tick.
 *
 * # Errors / safety
 *
 * Always returns a non-null `*mut ClientVerifier`. Allocation failure
 * is not modeled (the verifier is `Sized`, no per-instance dynamic
 * allocation beyond the heap box for FFI ownership transfer). If a
 * future change introduces a fallible path, this function will
 * return null and update its docs.
 *
 * # Safety
 *
 * Caller MUST eventually call [`corelink_verifier_free`] exactly once
 * on the returned handle. Passing the handle to anything other than
 * the documented FFI entry points is undefined behavior.
 */
 CoreLinkClientVerifier *corelink_verifier_new_default_on(void);
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * Allocate a new **explicitly disabled** opaque `ClientVerifier`.
 *
 * Distinct C symbol from [`corelink_verifier_new_default_on`] so that
 * opt-out cannot happen by zero-initialization or argument-flag
 * confusion: the caller must deliberately reach for *this* symbol.
 *
 * # Inputs
 *
 * - `warn`: non-zero ⇒ emit `tracing::warn!`
 *   `client_verify=disabled; proceed at own risk` on construction.
 *   Zero ⇒ counter still ticks but no log fires (used by Python
 *   pyO3 `__del__`-driven teardown paths that cannot afford an
 *   extra log).
 *
 * # Errors / safety
 *
 * Always returns a non-null `*mut ClientVerifier`. Same notes as
 * [`corelink_verifier_new_default_on`] apply.
 *
 * # Safety
 *
 * Caller MUST eventually call [`corelink_verifier_free`] exactly once
 * on the returned handle.
 */
 CoreLinkClientVerifier *corelink_verifier_new_disabled(uint8_t warn);
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * Free an opaque verifier handle previously returned by either
 * [`corelink_verifier_new_default_on`] or
 * [`corelink_verifier_new_disabled`].
 *
 * # Safety
 *
 * `handle` MUST be a pointer previously returned by one of the
 * `corelink_verifier_new_*` constructors and not yet freed. Passing
 * any other pointer is undefined behavior. A null pointer is treated
 * as a no-op (consistent with `free(NULL)` C semantics).
 */
 void corelink_verifier_free(CoreLinkClientVerifier *handle);
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * Verify `body[..body_len]` against the hex-encoded digest in
 * `digest_hex[..digest_hex_len]`.
 *
 * Writes the canonical error tag into `*out_error_code` (see the
 * `COR_VERIFY_*` constants). The function return value mirrors
 * `*out_error_code` for callers that prefer not to thread an
 * out-pointer (Python, JS) — they are guaranteed to agree.
 *
 * # Inputs
 *
 * - `handle`: opaque `*const ClientVerifier` from
 *   [`corelink_verifier_new_default_on`] /
 *   [`corelink_verifier_new_disabled`].
 * - `body_ptr`, `body_len`: raw body to hash. `body_len == 0` is
 *   permitted (BLAKE3 is defined for empty input); in that case
 *   `body_ptr` MAY be null. `body_len` must be `<= isize::MAX`
 *   (slice creation precondition); larger lengths are rejected
 *   with `COR_VERIFY_ERR_INVALID_INPUT` *before* any pointer
 *   dereference.
 * - `digest_hex_ptr`, `digest_hex_len`: ASCII hex of the claimed
 *   digest. Must be exactly [`DIGEST_HEX_LEN`] (= 64) bytes.
 *   Any other length is rejected with
 *   `COR_VERIFY_ERR_INVALID_DIGEST` before the pointer is read,
 *   so a malformed length cannot trigger UB.
 * - `out_error_code`: must point to a writable `i32`. Receives the
 *   same value returned by the function. If the pointer is null,
 *   the function still returns the tag but cannot write through
 *   it (callers are advised to always supply a writable cell).
 *
 * # Safety
 *
 * Caller MUST ensure:
 * - `handle` is a live verifier pointer (or null — null is
 *   handled as `COR_VERIFY_ERR_INVALID_INPUT`).
 * - `body_ptr[..body_len]` is a valid readable slice (or
 *   `body_len == 0`).
 * - `digest_hex_ptr[..DIGEST_HEX_LEN]` is a valid readable slice
 *   of ASCII bytes when `digest_hex_len == DIGEST_HEX_LEN`. Other
 *   lengths are rejected without reading from the pointer.
 * - `out_error_code` is null OR points to a writable `i32`.
 */

int32_t corelink_verifier_verify(const CoreLinkClientVerifier *handle,
                                 const uint8_t *body_ptr,
                                 uintptr_t body_len,
                                 const uint8_t *digest_hex_ptr,
                                 uintptr_t digest_hex_len,
                                 int32_t *out_error_code);
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * Read the process-wide opt-out counter (mirror of
 * [`crate::opt_out_total`] in the C-ABI surface).
 *
 * SDK FFI wrappers (Python pyO3, Go cgo) call this to populate the
 * canonical `corelink_client_verify_optout_total{lang}` Grafana
 * metric without having to duplicate the accounting per language.
 * The counter is monotonic non-decreasing and never reset.
 *
 * # Safety
 *
 * Always safe to call. Returns the current u64 value at the moment
 * of the call; concurrent constructions of disabled verifiers may
 * race, so callers should treat the return as a sample rather than
 * a barrier-synchronized observation. `Ordering::Relaxed` is used
 * internally — see `verifier.rs` for rationale.
 */
 uint64_t corelink_verify_opt_out_total(void);
#endif

#if defined(CORELINK_CLIENT_VERIFY_FFI)
/**
 * Map an FFI error code to its canonical
 * `error_taxonomy.md` string. Returns a static null-terminated
 * pointer; callers MUST NOT free the returned pointer.
 *
 * # Safety
 *
 * Always safe to call. Returns `core::ptr::null()` for unknown codes
 * so SDK callers can detect a future-extended taxonomy without
 * crashing.
 */
 const char *corelink_verify_error_code_to_str(int32_t code);
#endif

#endif  /* CORELINK_CLIENT_VERIFY_H */
