import { Buffer } from "node:buffer";
import { mkdirSync, renameSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import type {
  FullConfig,
  FullResult,
  Reporter,
  TestCase,
  TestResult,
} from "@playwright/test/reporter";

export interface AuditViolation {
  id: string;
  impact: string | null;
  help: string;
  helpUrl: string;
  nodes: number;
  tags: string[];
}

export interface AuditResult {
  route: string;
  url: string;
  violations: AuditViolation[];
  error?: string;
}

interface ReporterOptions {
  outputFile?: string;
  summaryFile?: string;
}

const IMPACTS = ["critical", "serious", "moderate", "minor"] as const;

export function renderSummary(results: AuditResult[]): string {
  const totals = Object.fromEntries(IMPACTS.map((impact) => [impact, 0])) as Record<
    (typeof IMPACTS)[number],
    number
  >;
  const rows = results.map((result) => {
    const counts = Object.fromEntries(
      IMPACTS.map((impact) => [
        impact,
        result.violations.filter((violation) => violation.impact === impact).length,
      ]),
    ) as Record<(typeof IMPACTS)[number], number>;
    for (const impact of IMPACTS) totals[impact] += counts[impact];
    return `| \`${result.route}\` | ${result.violations.length} | ${counts.critical} | ${counts.serious} | ${counts.moderate} | ${counts.minor} |`;
  });
  const total = results.reduce((sum, result) => sum + result.violations.length, 0);
  return [
    "# WCAG 2.2 AA — axe-core audit",
    "",
    "Generated by `scripts/a11y-audit.sh` using `@axe-core/playwright`.",
    "",
    "| Route | Total | Critical | Serious | Moderate | Minor |",
    "| --- | ---: | ---: | ---: | ---: | ---: |",
    ...rows,
    `| **TOTAL** | **${total}** | **${totals.critical}** | **${totals.serious}** | **${totals.moderate}** | **${totals.minor}** |`,
    "",
  ].join("\n");
}

export function parseAuditAttachment(body: Buffer): AuditResult {
  const parsed: unknown = JSON.parse(body.toString("utf8"));
  if (
    typeof parsed !== "object" ||
    parsed === null ||
    !("route" in parsed) ||
    typeof parsed.route !== "string" ||
    !("url" in parsed) ||
    typeof parsed.url !== "string" ||
    !("violations" in parsed) ||
    !Array.isArray(parsed.violations)
  ) {
    throw new Error("invalid corelink-a11y-result attachment");
  }
  for (const violation of parsed.violations) {
    if (
      typeof violation !== "object" ||
      violation === null ||
      !("id" in violation) ||
      typeof violation.id !== "string" ||
      !("impact" in violation) ||
      (violation.impact !== null && typeof violation.impact !== "string") ||
      !("help" in violation) ||
      typeof violation.help !== "string" ||
      !("helpUrl" in violation) ||
      typeof violation.helpUrl !== "string" ||
      !("nodes" in violation) ||
      typeof violation.nodes !== "number" ||
      !("tags" in violation) ||
      !Array.isArray(violation.tags) ||
      !violation.tags.every((tag: unknown) => typeof tag === "string")
    ) {
      throw new Error("invalid violation in corelink-a11y-result attachment");
    }
  }
  return parsed as AuditResult;
}

function writeAtomically(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const temporary = `${path}.tmp-${process.pid}`;
  writeFileSync(temporary, contents, { encoding: "utf8", mode: 0o600 });
  renameSync(temporary, path);
}

export default class CoreLinkA11yReporter implements Reporter {
  private readonly results = new Map<string, AuditResult>();
  private outputFile?: string;
  private summaryFile?: string;

  constructor(options: ReporterOptions = {}) {
    this.outputFile = options.outputFile;
    this.summaryFile = options.summaryFile;
  }

  onBegin(_config: FullConfig): void {
    this.outputFile ??= process.env.A11Y_AUDIT_REPORT;
    this.summaryFile ??= process.env.A11Y_AUDIT_SUMMARY;
  }

  onTestEnd(test: TestCase, result: TestResult): void {
    const attachment = result.attachments.find(
      (candidate) => candidate.name === "corelink-a11y-result" && candidate.body,
    );
    const audit = attachment?.body
      ? parseAuditAttachment(attachment.body)
      : {
          route: test.title.replace(/^a11y:\s*/, ""),
          url: new URL(
            test.title.replace(/^a11y:\s*/, ""),
            process.env.DOCS_BASE_URL ?? "http://localhost:3000",
          ).href,
          violations: [],
          error: result.errors[0]?.message ?? `test ended with status ${result.status}`,
        };
    this.results.set(audit.route, audit);
  }

  onEnd(_result: FullResult): void {
    if (!this.outputFile) return;
    const results = [...this.results.values()].sort((left, right) =>
      left.route.localeCompare(right.route),
    );
    writeAtomically(this.outputFile, `${JSON.stringify(results, null, 2)}\n`);
    if (this.summaryFile) writeAtomically(this.summaryFile, renderSummary(results));
  }
}
