-- CoreLink D1 (Cloudflare SQLite) — migration 0009 for `quota_reservations`
-- (S-07 Quota enforcement middleware: per-tenant pending reservation table;
-- WI-S07-003 reservation lifecycle).
--
-- Canonical sources:
--   - specs/04_sprints/_sealed/S07/work_items/WI-S07-003-quota-enforcement-middleware.md §6.1.4
--   - specs/04_sprints/_sealed/S07/_spec_contract.md §5 R-S07-3 + §8 INV-QUOTA-RESERVATION-TTL
--   - specs/03_architecture/invariant_registry.md INV-QUOTA-RESERVATION-TTL
--   - specs/03_architecture/adrs/ADR-0020-quota-enforcement-ownership.md (FROZEN)
--   - specs/03_architecture/adrs/ADR-0036-d1-schema-migration-governance.md
--
-- Schema rationale:
--   - The DO singleton `quota-<tenant_id>` (production wiring; WI-S07-005 PRR
--     ship gate) holds pending reservations IN-MEMORY for hot-path latency
--     (≤ 3ms p99 per WI §10.s07.3 SLO). The SQL table here is the durable
--     mirror — DO writes the reservation row on `check_and_reserve`, removes
--     it on `commit_reservation` (rolling bytes into `tenant_storage_state`)
--     or `release_reservation` (TTL expiry / explicit release).
--   - On DO cold start, the reservation rows are reloaded so pending
--     reservations are not lost across worker restarts.
--   - Reservation TTL is size-proportional per Lote 10.7bis R5 P0-2:
--     `ttl_ms = max(60_000, request_bytes / 1024 × 2)` capped 7d.
--     `expires_at_ms = created_at_ms + ttl_ms`. The DO alarm cleanup
--     scans the table every 60s and deletes expired rows.
--   - PROVISIONAL boundary (transitional per ADR-0020 FROZEN): the 100% hard-block
--     429 + Retry-After arm in the middleware is provisional; canonical
--     `Retry-After: days-until-month-reset` ships in S-08 CAP-QUOTA-001.
--
-- Invariants enforced at storage layer:
--   - INV-TENANT-ISOLATION (CRITICAL): tenant_id is the leftmost PK component;
--     cross-tenant reservation injection FM-300 impossible by design.
--   - INV-QUOTA-RESERVATION-TTL (HIGH): every reservation row carries
--     `expires_at_ms`; a row whose `expires_at_ms < now` MUST be reclaimed
--     by the DO alarm cleanup OR a periodic D1 sweeper (no quota leak).
--   - INV-QUOTA-ENFORCEMENT (HIGH): the DO singleton owns the canonical
--     `bytes_used + sum(active_reservations.bytes)` invariant; this table
--     is the durable mirror.
--
-- Conventions (mirror migrations/d1/0001..0008):
--   - tenant_id stored as canonical UUIDv7 TEXT form (data_model.md §2.1).
--   - reservation_id stored as canonical UUIDv7 TEXT form (per-reservation
--     identity; generated by the DO on `check_and_reserve`).
--   - region stored as canonical 5-region literal (sam/iad/lhr/nrt/syd) with
--     CHECK constraint (mirrors gc_run.region + tenant_storage_state.region).
--   - All timestamps stored as INTEGER Unix epoch milliseconds.
--   - Migration is idempotent via `CREATE TABLE IF NOT EXISTS` /
--     `CREATE INDEX IF NOT EXISTS`.
--   - Migrations are additive-only per scripts/check_migrations_additive.py
--     CI gate.
--
-- D1 SQL correctness gates (Lote 10.4bis P0 lessons; pre-deploy CI):
--   - sqlite3 :memory: < migrations/d1/0009_quota_reservations.sql executes
--     without error (caught at parser level antes deploy via crates/corelink-quota
--     migration_canonical_0009 test).
--   - CHECK constraints inlined in CREATE TABLE (SQLite/D1 does NOT support
--     `ALTER TABLE … ADD CONSTRAINT chk_*`; only inline at CREATE TABLE per
--     ADR-0036 Rule 1).
--   - BEGIN/COMMIT NOT included (`wrangler d1 migrations apply` uses an
--     implicit transaction).
--
-- Backfill plan: NONE. The table starts empty; reservations are inserted
-- by the DO singleton on first `check_and_reserve` post-deploy.
--
-- Migration runner: see scripts/migrate_d1.sh.

-- ---------------------------------------------------------------------------
-- quota_reservations — per-(tenant, region) pending reservation rows.
--
-- ONE row per (tenant_id, reservation_id) — composite PK with tenant-leftmost
-- ordering. region is denormalized for DO routing per tenant.primary_region
-- (Lote 10.7bis P0-9). expires_at_ms drives the auto-release TTL sweep.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quota_reservations (
  -- Tenant scope (PK component 1; tenant-leftmost per data_model.md §2.1).
  tenant_id              TEXT     NOT NULL,

  -- Reservation identity (PK component 2; canonical UUIDv7 generated by the
  -- DO at check_and_reserve time; client never sees this directly).
  reservation_id         TEXT     NOT NULL,

  -- Region scope (denormalized; canonical 5-region literal list).
  region                 TEXT     NOT NULL,

  -- Bytes reserved by THIS reservation (the `request_bytes` of the
  -- in-flight write that owns the reservation). Monotone immutable —
  -- once reserved, the value never changes (commit rolls it into
  -- bytes_used; release/expiry removes the row).
  requested_bytes        INTEGER  NOT NULL,

  -- Expiration watermark (Unix ms). Computed at INSERT time as
  -- `created_at_ms + reservation_ttl_ms(requested_bytes)` per the canonical
  -- size-proportional formula `max(60_000, requested_bytes/1024 × 2), capped 7d`
  -- (Lote 10.7bis R5 P0-2). The DO alarm cleanup deletes rows with
  -- `expires_at_ms < now`.
  expires_at_ms          INTEGER  NOT NULL,

  -- Creation watermark (Unix ms; immutable).
  created_at_ms          INTEGER  NOT NULL,

  -- Composite PK — tenant-leftmost; (tenant, reservation_id) per
  -- WI-S07-003 §6.1 reservation lifecycle.
  PRIMARY KEY (tenant_id, reservation_id),

  -- chk_quota_reservations_region: canonical 5-region literal list
  -- (mirrors tenant_storage_state.region + gc_run.region domain).
  CHECK (region IN ('sam', 'iad', 'lhr', 'nrt', 'syd')),
  -- chk_quota_reservations_requested_bytes_non_negative.
  CHECK (requested_bytes >= 0),
  -- chk_quota_reservations_ttl_after_create: expires_at_ms > created_at_ms
  -- (every reservation has a strictly positive TTL window).
  CHECK (expires_at_ms > created_at_ms),
  -- chk_quota_reservations_lifecycle_create_non_negative.
  CHECK (created_at_ms >= 0)
);

-- Index: per-(tenant, region) scan for the eviction pass + DO consistency
-- check. Composite PK already supports per-tenant lookup; this secondary
-- index supports the per-region scan.
CREATE INDEX IF NOT EXISTS idx_quota_reservations_tenant_region
  ON quota_reservations(tenant_id, region);

-- Index: TTL sweep — the DO alarm cleanup + periodic D1 sweeper scan
-- `WHERE expires_at_ms < now` to reclaim leaked reservations.
CREATE INDEX IF NOT EXISTS idx_quota_reservations_expires_at_ms
  ON quota_reservations(expires_at_ms);
