"""Markdown rendering for the compliance weekly digest."""
from __future__ import annotations

from datetime import date, datetime
from typing import Any

from compliance_weekly_digest_model import DigestPayload
from compliance_weekly_digest_sources import COMPLIANCE_DIR, parse_gap_register

# Markdown renderer
# ─────────────────────────────────────────────────────────────────────────────


def _fmt_delta(v: float) -> str:
    if v > 0:
        return f"+{v:.1f}%"
    if v < 0:
        return f"{v:.1f}%"
    return "no change"


def render_markdown(p: DigestPayload) -> str:
    lines: list[str] = []
    lines.append(f"# Compliance Weekly Digest — {p.digest_date.isoformat()}")
    lines.append("")
    lines.append(
        f"> **SOC 2 CC4.2 evidence** · auto-generated by "
        f"`scripts/compliance-weekly-digest.py` · reference digest: "
        f"`{p.reference_digest or '(none — first digest)'}` · "
        f"regression: **{'YES' if p.regression else 'NO'}**."
    )
    lines.append("")

    # Section 1 — readiness.
    lines.append("## 1. SOC 2 Readiness")
    lines.append("")
    lines.append(
        f"Source rollup: `{p.readiness.rollup_path}` "
        f"({p.readiness.implemented_count} I / {p.readiness.partial_count} P / "
        f"{p.readiness.gap_count} G by criterion-count)."
    )
    lines.append("")
    lines.append("| Metric | Now | Δ vs last week |")
    lines.append("|---|---|---|")
    lines.append(f"| Implemented: {p.readiness.implemented_pct}% | {p.readiness.implemented_pct}% | {_fmt_delta(p.readiness_delta['implemented_pct'])} |")
    lines.append(f"| Partial: {p.readiness.partial_pct}% | {p.readiness.partial_pct}% | {_fmt_delta(p.readiness_delta['partial_pct'])} |")
    lines.append(f"| Gap: {p.readiness.gap_pct}% | {p.readiness.gap_pct}% | {_fmt_delta(p.readiness_delta['gap_pct'])} |")
    lines.append(f"| Drata dashboard: {p.readiness.drata_dashboard_pct}% | {p.readiness.drata_dashboard_pct}% | {_fmt_delta(p.readiness_delta['drata_dashboard_pct'])} |")
    lines.append(f"| Internal scorecard | {p.readiness.internal_scorecard_pct}% | (n/a — sourced from rollup direct) |")
    lines.append(f"| Auto-collection rate | {p.readiness.auto_collection_pct}% | (n/a) |")
    lines.append("")

    # Section 2 — GAP register delta.
    lines.append("## 2. GAP register delta")
    lines.append("")
    lines.append(
        f"- Open GAPs: **{p.gap_delta.total_open_now}** "
        f"(prev: {p.gap_delta.total_open_prev})"
    )
    lines.append(f"- New: {', '.join(p.gap_delta.new) or '—'}")
    lines.append(f"- Closed: {', '.join(p.gap_delta.closed) or '—'}")
    lines.append(
        "- Severity upgrade: "
        + (", ".join(f"{g[0]} ({g[1]}→{g[2]})" for g in p.gap_delta.severity_up) or "—")
    )
    lines.append(
        "- Severity downgrade: "
        + (", ".join(f"{g[0]} ({g[1]}→{g[2]})" for g in p.gap_delta.severity_down) or "—")
    )
    lines.append("")

    # Section 3 — vendor risk.
    lines.append("## 3. Vendor risk SLAs")
    lines.append("")
    if p.vendor_breaches:
        # Every row in this table is ALREADY past its cadence window — the table
        # is built from `sla_breach` vendors only. Say so in prose: a reader who
        # scans just the verdict column would otherwise read "no" as "healthy",
        # when it only means the breach has not yet DOUBLED the window (which is
        # the §7 regression trigger). An overdue review that reads as clean is
        # the same defect class as a cron that skips and logs nothing.
        crit = sum(1 for v in p.vendor_breaches if v.category == "Critical")
        doubled = sum(1 for v in p.vendor_breaches if v.sla_2x_breach)
        lines.append(
            f"⚠️ **{len(p.vendor_breaches)} vendor review(s) OVERDUE** "
            f"({crit} Critical) — every row below is past its cadence window. "
            f"{doubled} of them have passed 2× the window "
            f"({'a §7 regression trigger' if doubled else 'the §7 regression trigger'})."
        )
        lines.append("")
        lines.append(
            "| Vendor | Tier | Days since review | SLA window | Days overdue | > 2× cadence? | Owner |"
        )
        lines.append("|---|---|---|---|---|---|---|")
        for v in p.vendor_breaches:
            lines.append(
                f"| {v.vendor} | {v.category} | {v.days_since} | "
                f"{v.cadence_days}d | +{v.days_since - v.cadence_days} | "
                f"{'YES' if v.sla_2x_breach else 'no'} | {v.owner} |"
            )
    else:
        lines.append("All registered vendors within SLA. No breaches.")
    lines.append("")

    # Section 4 — drill cadence.
    lines.append("## 4. Drill cadence flags")
    lines.append("")
    if p.drill_flags:
        lines.append("| Drill ID | Criticality | Days overdue | Evidence file present? |")
        lines.append("|---|---|---|---|")
        for d in p.drill_flags:
            lines.append(
                f"| {d.drill_id} | {d.criticality} | {d.days_overdue} | "
                f"{'yes' if d.evidence_present else 'NO'} |"
            )
    else:
        lines.append("No drill missed past grace window.")
    lines.append("")

    # Section 5 — IR tabletop next session.
    lines.append("## 5. IR tabletop — next session")
    lines.append("")
    if p.next_tabletop:
        nt = p.next_tabletop
        lines.append(
            f"- **{nt.tt_id}** — target {nt.target_date.isoformat()} "
            f"(backup {nt.backup_date.isoformat()}); T-{nt.days_to_session}d to session."
        )
        lines.append(
            f"- T-7d brief readiness: {'IN WINDOW' if nt.t_minus_7_brief else 'pending'}"
        )
        lines.append(
            f"- Scenario / facilitator artefact present: "
            f"{'yes' if nt.facilitator_assigned else 'MISSING'}"
        )
    else:
        lines.append("No future tabletop session scheduled — review `IR-TABLETOP-SCHEDULE-2026.md`.")
    lines.append("")

    # Section 6 — CI compliance-gate failures.
    lines.append("## 6. Compliance-gate CI failures (last 7 days)")
    lines.append("")
    if p.ci_failures:
        lines.append("| Workflow | Conclusion | Finished | Run |")
        lines.append("|---|---|---|---|")
        for f in p.ci_failures:
            lines.append(
                f"| {f.workflow} | {f.conclusion} | {f.finished_at} | {f.run_url} |"
            )
    else:
        lines.append("No failed compliance-gate workflows in the last 7 days.")
    lines.append("")

    # Section 7 — regression verdict + GAP register snapshot.
    lines.append("## 7. Regression verdict")
    lines.append("")
    if p.regression:
        lines.append("**REGRESSION DETECTED.** Reasons:")
        lines.append("")
        for r in p.regression_reasons:
            lines.append(f"- {r}")
        lines.append("")
        lines.append(
            "Escalation: page Compliance on-call via PagerDuty service "
            "`corelink-compliance`. Runbook: "
            "`specs/_runbooks/RB-COMPLIANCE-WEEKLY-REVIEW.md` §4."
        )
    else:
        lines.append(
            "No regression detected. Compliance posture stable or improving. "
            "Triage runbook still requires Compliance Lead acknowledgement "
            "(`specs/_runbooks/RB-COMPLIANCE-WEEKLY-REVIEW.md` §3)."
        )
    lines.append("")

    # Section 8 — GAP snapshot (regression-detector hook for next week).
    lines.append("## 8. GAP register snapshot (digest-internal)")
    lines.append("")
    lines.append("> This table is the canonical state the next digest will diff against.")
    lines.append("")
    lines.append("| GAP ID | Severity | Status |")
    lines.append("|---|---|---|")
    gap_now = parse_gap_register(COMPLIANCE_DIR / "SOC2-GAP-ANALYSIS.md")
    for gid in sorted(gap_now):
        g = gap_now[gid]
        lines.append(f"| {gid} | {g.severity} | {g.status} |")
    lines.append("")

    # Section 10 — TLA verification status (R5-3 expansion).
    lines.append("## 10. TLA verification status (R5-3 expansion)")
    lines.append("")
    lines.append(f"Source: `{p.tla_floors.source}` (ratchet floors).")
    lines.append("")
    lines.append("| Floor | Current | Previous | Regressed? |")
    lines.append("|---|---|---|---|")
    for f in p.tla_floors.floors:
        prev = f.previous if f.previous is not None else "—"
        flag = "HARD FAIL" if f.regressed else "no"
        lines.append(f"| {f.name} | {f.current} | {prev} | {flag} |")
    lines.append(
        f"| orphan_refs | {p.tla_floors.orphan_refs} | (must be 0) | "
        f"{'HARD FAIL' if p.tla_floors.orphan_refs > 0 else 'no'} |"
    )
    lines.append("")
    if p.tla_floors.any_regression:
        lines.append(
            "**Escalation:** any HARD FAIL row pages PD service "
            "`corelink-compliance` (SEV-2) — see "
            "`specs/_runbooks/RB-COMPLIANCE-WEEKLY-REVIEW.md` §4.x and "
            "`specs/_runbooks/RB-CANONICAL-DRIFT.md` §6."
        )
    else:
        lines.append("No TLA ratchet regression. Floors stable or rising.")
    lines.append("")

    # Section 11 — Mutation kill rate trend (R5-3 expansion).
    lines.append("## 11. Mutation kill rate trend (R5-3 expansion)")
    lines.append("")
    if p.mutation_trend.crates:
        lines.append("| Crate | Kill rate | Source audit | < 75% floor? |")
        lines.append("|---|---|---|---|")
        for c in p.mutation_trend.crates:
            lines.append(
                f"| {c.crate} | {c.kill_rate_pct:.2f}% | `{c.source}` | "
                f"{'YES — HARD FAIL' if c.below_floor else 'no'} |"
            )
    else:
        lines.append(
            "No mutation audits parsed (TBD — real source landing in "
            "Sprint R-3 `mutation-nightly.yml` artifact ingestion)."
        )
    lines.append("")
    if p.mutation_trend.any_below_floor:
        lines.append(
            "**Escalation:** any crate below 75% floor pages PD service "
            "`corelink-compliance` (SEV-3); owner files a follow-on WI "
            "to add targeted tests on missed mutants."
        )
    lines.append("")

    # Section 12 — Replication SLO compliance (R5-3 expansion).
    lines.append("## 12. Replication SLO compliance (R5-3 expansion)")
    lines.append("")
    lines.append(
        f"Verifier mode: `{p.replication.mode}` · rolling-30d breach streak: "
        f"**{p.replication.rolling_30d_streak}** consecutive week(s) · "
        f"any breach this week: **{'YES' if p.replication.any_breach else 'NO'}** · "
        f"rolling violation: **{'YES' if p.replication.rolling_breach else 'NO'}**."
    )
    lines.append("")
    if p.replication.domains:
        lines.append("| Domain | SLO ID | p99 lag (s) | RPO budget (s) | Breach? |")
        lines.append("|---|---|---|---|---|")
        for d in p.replication.domains:
            lines.append(
                f"| {d.domain} | {d.slo_id} | {d.p99_lag_secs:.2f} | "
                f"{d.budget_secs:.2f} | {'YES' if d.breach else 'no'} |"
            )
    else:
        lines.append(
            "No domain rows emitted (TBD — real Prometheus snapshot landing "
            "post-DEBT-011 P2 closure; inmemory fixture currently returns "
            "synthetic-pass payload)."
        )
    lines.append("")
    if p.replication.rolling_breach:
        lines.append(
            "**Escalation:** rolling-30d streak ≥ 3 → SEV-2 page; "
            "Replication SRE Lead opens `WI-REPLICATION-SLO-DRIFT` and "
            "cross-references `specs/_audits/sealed/2026-05-15-replication-audit.md`."
        )
    lines.append("")

    # Section 13 — Customer dashboard P0/P1 incident count (R5-3 expansion).
    lines.append("## 13. Customer dashboard P0/P1 incident count (R5-3 expansion)")
    lines.append("")
    lines.append(
        f"Source: `git log --grep='^incident:' --since=<window>` "
        f"+ `specs/_audits/*ir-tabletop-meta-retro*.md` "
        f"+ `specs/_audits/*-compliance-regression-*.md`."
    )
    lines.append("")
    lines.append("| Window | P0 incidents | P1 incidents |")
    lines.append("|---|---|---|")
    lines.append(f"| Last 7 days  | {p.incidents.p0_count_7d}  | {p.incidents.p1_count_7d}  |")
    lines.append(f"| Last 30 days | {p.incidents.p0_count_30d} | {p.incidents.p1_count_30d} |")
    lines.append("")
    if p.incidents.sample_commits:
        lines.append("Sample (last 7d):")
        for c in p.incidents.sample_commits:
            lines.append(f"- `{c}`")
        lines.append("")
    if p.incidents.retro_files:
        lines.append(
            f"Cross-referenced retro / regression audits: "
            f"**{len(p.incidents.retro_files)}** total."
        )
    if p.incidents.flagged:
        lines.append("")
        lines.append(
            "**Escalation:** P0 in last 7d (any) OR ≥ 2 P0 in rolling 30d "
            "→ SEV-2 page; IC opens post-incident retro within 7d per "
            "`specs/_compliance/IR-TABLETOP-PLAYBOOK.md` §9."
        )
    lines.append("")

    # Section 14 — Debt register burn-down (R5-3 expansion).
    lines.append("## 14. Debt register burn-down (R5-3 expansion)")
    lines.append("")
    lines.append(f"Source: `{p.debt.source}`.")
    lines.append("")
    lines.append(
        f"- Open debts: **{p.debt.open_count}** (prev: {p.debt.open_prev}; "
        f"Δ {p.debt.open_count - p.debt.open_prev:+d})"
    )
    lines.append(
        f"- Closed debts: **{p.debt.closed_count}** (prev: {p.debt.closed_prev}; "
        f"Δ {p.debt.closed_count - p.debt.closed_prev:+d})"
    )
    lines.append(f"- Partial debts: **{p.debt.partial_count}**")
    lines.append("")
    # Tier breakdown.
    by_tier: dict[str, dict[str, int]] = {
        "P0": {"OPEN": 0, "CLOSED": 0, "PARTIAL": 0},
        "P1": {"OPEN": 0, "CLOSED": 0, "PARTIAL": 0},
        "P2": {"OPEN": 0, "CLOSED": 0, "PARTIAL": 0},
    }
    for r in p.debt.rows:
        if r.tier in by_tier:
            by_tier[r.tier][r.status] = by_tier[r.tier].get(r.status, 0) + 1
    lines.append("| Tier | OPEN | PARTIAL | CLOSED |")
    lines.append("|---|---|---|---|")
    for tier in ("P0", "P1", "P2"):
        b = by_tier[tier]
        lines.append(
            f"| {tier} | {b.get('OPEN', 0)} | {b.get('PARTIAL', 0)} | "
            f"{b.get('CLOSED', 0)} |"
        )
    lines.append("")
    if p.debt.p0_overdue:
        lines.append("**HARD FAIL — P0 rows past Target without CLOSED marker:**")
        lines.append("")
        for did in p.debt.p0_overdue:
            row = next((r for r in p.debt.rows if r.debt_id == did), None)
            tgt = row.target_date.isoformat() if row and row.target_date else "(none)"
            lines.append(f"- {did} — Target {tgt}")
        lines.append("")
        lines.append(
            "**Escalation:** SEV-2 page; Owner (Gustavo) signs waiver in "
            "`specs/_audits/<latest>-debt-register.md §5` or closes the "
            "row within 7d per the register's hard mandate."
        )
    else:
        lines.append("All P0 debt rows either CLOSED or within Target window.")
    lines.append("")

    # Section 15 — companion docs (was §9 pre-R5-3; renumbered to keep
    # §10..§14 as the new domains in ascending order).
    lines.append("## 15. Cross-links")
    lines.append("")
    lines.append("- Triage runbook: `specs/_runbooks/RB-COMPLIANCE-WEEKLY-REVIEW.md`")
    lines.append("- Methodology + index: `specs/_compliance/weekly-digests/README.md`")
    lines.append("- SOC 2 evidence rollup: `specs/_compliance/SOC2-EVIDENCE-ROLLUP-2026-05-15.md` §2.4 (CC4.2)")
    lines.append("- GAP register: `specs/_compliance/SOC2-GAP-ANALYSIS.md` §CC4.2 (GAP-08 closed)")
    lines.append("- Vendor risk: `specs/_compliance/VENDOR-RISK-REGISTER.md`")
    lines.append("- Drill cadence: `specs/_compliance/BCP-DR-DRILL-CADENCE.md`")
    lines.append("- IR tabletop schedule: `specs/_compliance/IR-TABLETOP-SCHEDULE-2026.md`")
    lines.append("- Roadmap §9 (Human Track): `ROADMAP-TO-GA.md`")
    lines.append(
        "- (R5-3 expansion) Canonical consistency baseline: "
        f"`{p.tla_floors.source}`"
    )
    lines.append(
        "- (R5-3 expansion) Replication verifier: "
        "`scripts/verify-replication-lag.py`"
    )
    lines.append(
        "- (R5-3 expansion) Debt register: "
        f"`{p.debt.source}`"
    )
    lines.append(
        "- (R5-3 expansion) IR tabletop playbook (post-incident retros): "
        "`specs/_compliance/IR-TABLETOP-PLAYBOOK.md`"
    )
    lines.append("")
    return "\n".join(lines) + "\n"


# ─────────────────────────────────────────────────────────────────────────────
__all__ = ["_fmt_delta", "render_markdown"]
