#!/usr/bin/env python3
"""
Deterministically regenerate the OKF-CoreLink bundle index (`docs/knowledge/index.md`).

Walks the knowledge bundle, finds every concept doc (every non-reserved `.md`),
groups them by taxonomy directory (profile §1.1), and writes a machine-generated
listing with a bundle-relative link (leading `/`) and the concept's title.

This is a pure, stdlib-only, no-LLM generator. It is idempotent: running it twice
in a row produces a byte-identical `index.md`. It transcribes the frozen contract
`docs/internal/okf-wiki/01-okf-corelink-profile.contract.md` (§1, §1.1, §2.3).

Usage:
    python3 scripts/okf_index.py            # regenerate in place
    python3 scripts/okf_index.py --check     # exit 1 if index.md is out of date (no write)

Exit:
    0  index.md is current (or was regenerated).
    1  --check and index.md differs from the freshly generated content.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BUNDLE = REPO_ROOT / "docs" / "knowledge"
INDEX = BUNDLE / "index.md"

# Reserved root files (profile §1) — never concepts, never listed as concepts.
RESERVED = {"index.md", "log.md"}
# Subdir holding immutable cited artifacts, not concepts (profile §1).
NON_CONCEPT_DIRS = {"references"}

# Frozen taxonomy order (profile §1.1). Dirs not in this list sort after, alpha.
TAXONOMY_ORDER = [
    "planes",
    "surfaces",
    "auth",
    "storage",
    "tenancy",
    "flows",
    "crates",
    "adr",
    "ops",
    "security",
    "compliance",
    "testing",
    "launch",
]

FRONT_MATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def parse_front_matter(text: str) -> dict[str, str]:
    """Minimal, dependency-free YAML-frontmatter scalar reader.

    Only the flat scalar keys we need (title, type, deferred) are read. Values
    may be single/double quoted or bare. Block/list keys are ignored.
    """
    match = FRONT_MATTER_RE.match(text)
    out: dict[str, str] = {}
    if not match:
        return out
    for line in match.group(1).splitlines():
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", line)
        if not m:
            continue
        key, raw = m.group(1), m.group(2).strip()
        if raw == "" or raw.startswith(("#", "-", "[", "{")):
            # empty (block scalar / list follows) or inline collection — skip.
            continue
        if (raw.startswith('"') and raw.endswith('"')) or (
            raw.startswith("'") and raw.endswith("'")
        ):
            raw = raw[1:-1]
        out[key] = raw
    return out


def find_concepts() -> list[tuple[str, str, str]]:
    """Return sorted (taxonomy_dir, concept_id, title) for every concept doc.

    concept_id = bundle-relative path minus `.md` (profile §1).
    """
    concepts: list[tuple[str, str, str]] = []
    for path in sorted(BUNDLE.rglob("*.md")):
        rel = path.relative_to(BUNDLE)
        parts = rel.parts
        # Reserved root files are not concepts.
        if len(parts) == 1 and parts[0] in RESERVED:
            continue
        # Non-concept subdirs (references/) hold artifacts, not concepts.
        if parts[0] in NON_CONCEPT_DIRS:
            continue
        taxonomy = parts[0] if len(parts) > 1 else "(root)"
        concept_id = str(rel.with_suffix(""))
        fm = parse_front_matter(path.read_text(encoding="utf-8"))
        title = fm.get("title") or concept_id
        concepts.append((taxonomy, concept_id, title))
    return concepts


def taxonomy_sort_key(name: str) -> tuple[int, str]:
    if name in TAXONOMY_ORDER:
        return (TAXONOMY_ORDER.index(name), name)
    return (len(TAXONOMY_ORDER), name)


def render(concepts: list[tuple[str, str, str]]) -> str:
    total = len(concepts)
    groups: dict[str, list[tuple[str, str]]] = {}
    for taxonomy, concept_id, title in concepts:
        groups.setdefault(taxonomy, []).append((concept_id, title))

    lines: list[str] = []
    lines.append("---")
    lines.append("type: Index")
    lines.append("title: \"OKF-CoreLink knowledge bundle — index\"")
    lines.append("okf_version: '0.1'")
    lines.append("profile_version: '0.1'")
    lines.append("---")
    lines.append("")
    lines.append("# OKF-CoreLink knowledge bundle — index")
    lines.append("")
    lines.append(
        "> GENERATED — do not hand-edit. Regenerated by `scripts/okf_index.py` by walking "
        "the bundle. Run `python3 scripts/okf_index.py` after adding/removing a concept."
    )
    lines.append("")
    lines.append(
        "This is the reserved machine-generated listing of every concept in `docs/knowledge/` "
        "(profile §1 / §2.3). Concepts are grounded code/docs knowledge; author new ones with "
        "`scripts/okf_scaffold.py` and re-run this generator. The frozen contract lives outside the "
        "bundle at `docs/internal/okf-wiki/01-okf-corelink-profile.contract.md`; the change history "
        "is in `/log.md`."
    )
    lines.append("")
    lines.append(f"**Concepts: {total}**")
    lines.append("")

    if total == 0:
        lines.append("_No concepts yet. Empty conformant bundle (0 concepts, 0 stale)._")
        lines.append("")
    else:
        for taxonomy in sorted(groups, key=taxonomy_sort_key):
            lines.append(f"## {taxonomy}")
            lines.append("")
            for concept_id, title in sorted(groups[taxonomy]):
                lines.append(f"- [{title}](/{concept_id}.md)")
            lines.append("")

    # Normalize: drop trailing blanks, end with exactly one newline.
    while lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if index.md differs from freshly generated content (no write).",
    )
    args = parser.parse_args()

    if not BUNDLE.is_dir():
        sys.exit(f"ERROR: bundle root not found: {BUNDLE}")

    content = render(find_concepts())

    if args.check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != content:
            print("⛔ index.md is out of date — run `python3 scripts/okf_index.py`.")
            return 1
        print("✅ index.md is current.")
        return 0

    INDEX.write_text(content, encoding="utf-8")
    n = content.count("](/")
    print(f"✅ Regenerated {INDEX.relative_to(REPO_ROOT)} — {n} concept(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
