//! First PAT hash + shown-once token canonical newtypes.
//!
//! Per WI §6.1.4 + spec contract data_model §4.1 + CTRL-CRED-001: the
//! first PAT is auto-generated by the orchestrator at signup; the **raw
//! PAT NEVER persists plaintext** anywhere (D1 row stores `PatHash` via
//! hybrid HMAC + Argon2id per S-03 canonical format); the raw PAT is
//! surfaced to the user exactly once via a `ShownOnceToken` UUID v7
//! whose first-`GET` invalidates the token (subsequent GETs return
//! 410 Gone). This crate carries only the hash + the opaque token
//! identifier; the raw PAT material NEVER enters [`crate::request::SignupRequest`]
//! (CTRL-CRED-001 — PAT material NOT in signup payload; PAT is issued
//! by the orchestrator, not supplied by the caller; the WI-S19-006 flow
//! owns the user-facing reveal endpoint).

/// First-PAT hash newtype — opaque hex/base64 string. Production wiring
/// is hybrid HMAC + Argon2id per S-03 canonical format.
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct PatHash(String);

impl PatHash {
    /// Construct a new pat hash from any string-like value.
    #[must_use]
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Borrow the underlying string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl core::fmt::Display for PatHash {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Shown-once reveal token — UUID v7 string in production wiring. The
/// WI-S19-006 reveal endpoint invalidates the token on first GET; the
/// orchestrator records the token in the `pat` row + emits an audit
/// event but NEVER returns the raw PAT in the [`SignupResponse`] body.
///
/// [`SignupResponse`]: crate::orchestrator::SignupResponse
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ShownOnceToken(String);

impl ShownOnceToken {
    /// Construct a new shown-once token from any string-like value.
    #[must_use]
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Borrow the underlying string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl core::fmt::Display for ShownOnceToken {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(&self.0)
    }
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    reason = "tests are allowed to use these primitives"
)]
mod tests {
    use super::*;

    #[test]
    fn newtypes_round_trip() {
        let h = PatHash::new("abc123");
        let t = ShownOnceToken::new("uuid-1");
        assert_eq!(h.as_str(), "abc123");
        assert_eq!(t.as_str(), "uuid-1");
    }
}
